name: HighOnGravity
favicon: null
layout_spectrum: 0.84166
typography_spectrum: 0.41272
title: High On Gravity Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.9054237853270024
  rhythmicContrast: 0.75
purpose: []
