name: HighOnGravity
favicon: null
layout_spectrum: 0.84615
typography_spectrum: 0.38736
title: High On Gravity Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#9f9f9f'
    - '#7c7c7c'
    - '#575757'
    - '#c3c3c3'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
